import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import NewTaskDialog from "@/components/new-task/new-task-dialog";
import OverlayBackdrop from "@/components/overlay-backdrop";
import TaskDialog from "@/components/task/task-dialog";
import { clsx } from "clsx";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx("bg-app-very-dark-grey", plusJakartaSans.className)}
      >
        {children}

        <TaskDialog />
        <NewTaskDialog />
        <OverlayBackdrop />
      </body>
    </html>
  );
}
